Models/Bajas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ProyectoInventarioASP.Models;

public class Bajas
{
    [Key]
    public int id { get; set; }
    [Required(ErrorMessage = "Este Campo es requerido")]
    [Display(Name = "Inventario")]
    public string NumInv { get; set; }

    [Required(ErrorMessage = "Este Campo es requerido")]
    [Display(Name = "Serial")]
    public String NumSerie { get; set; }
    [Display(Name = "Marca")]
    [Required(ErrorMessage = "Este Campo es requerido")]
    public String Marca { get; set; }
    [Required(ErrorMessage = "Este Campo es requerido")]
    [Display(Name = "Fecha de baja")]
    public DateTime fechaBaja { get; set; }

    [Required(ErrorMessage = "Este Campo es requerido")]
    [Display(Name = "Equipo")]
    public string Equipo { get; set; }

    [Required(ErrorMessage = "Este Campo es requerido")]
    [Display(Name = "MotherBoard Serial")]
    public string SerieBoard { get; set; }

    [JsonIgnore]
    [NotMapped]
    public virtual List<DiscoDuro> Discos { get; set; }
    [JsonIgnore]
    [NotMapped]
    public virtual List<MemoriaRam> Memorias { get; set; }

    [NotMapped]
    public virtual MotherBoard MotherBoard { get; set; }

    [NotMapped]
    public virtual MicroProcesador Micro { get; set; }


}

Controllers/BajasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoInventarioASP;
using ProyectoInventarioASP.Models;
using Rotativa.AspNetCore;

namespace ProyectoInventarioASP.Controllers
{
    [Authorize]
    public class BajasController : Controller
    {
        private readonly ComputadoraContext _context;

        public BajasController(ComputadoraContext context)
        {
            _context = context;
        }

        // GET: Bajas
        public async Task<IActionResult> Index()
        {
            return _context.Bajas != null ?
                        View(await _context.Bajas.ToListAsync()) :
                        Problem("Entity set 'ComputadoraContext.Bajas'  is null.");
        }

        // GET: Bajas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bajas == null)
            {
                return NotFound();
            }

            var bajas = await _context.Bajas
                .FirstOrDefaultAsync(m => m.id == id);

            var boardId = CargarMotherboardId(bajas.NumInv);
            var marcaBoard = CargarMotherboardMarca(boardId);
            var discos = CargarDisco(boardId);
            var memorias = CargarMemorias(boardId);
            var microId = CargarMicroId(bajas.NumInv);
            var microTecn = CargarTecnMicro(microId);

            var modeloBaja = baja(bajas.id, bajas.Equipo, bajas.fechaBaja, bajas.NumInv, bajas.NumSerie, bajas.Marca, discos, memorias, boardId, microTecn, marcaBoard);

            if (bajas == null)
            {
                return NotFound();
            }

            return View(modeloBaja);
        }





        // GET: Bajas/Edit/5
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bajas == null)
            {
                return NotFound();
            }

            var boards = await _context.MotherBoards.Where(b => b.estado == Estado.inactivo).ToListAsync();
            ViewBag.Boards = boards;


            var bajas = await _context.Bajas.FindAsync(id);

            if (bajas.SerieBoard != "-")
            {
                var board = boards.FirstOrDefault(b => b.NumSerieBoard == bajas.SerieBoard);
                bajas.SerieBoard = board.NumSerieBoard;
                return View(bajas);
            }

            if (bajas == null)
            {
                return NotFound();
            }
            return View(bajas);
        }

        // POST: Bajas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bajas bajas)
        {
            if (id != bajas.id)
            {
                return NotFound();
            }

            if (bajas != null)
            {
                try
                {
                    _context.Update(bajas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BajasExists(bajas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bajas);
        }

        // GET: Bajas/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bajas == null)
            {
                return NotFound();
            }

            var bajas = await _context.Bajas
                .FirstOrDefaultAsync(m => m.id == id);

            var boardId = CargarMotherboardId(bajas.NumInv);
            var marcaBoard = CargarMotherboardMarca(boardId);
            var discos = CargarDisco(boardId);
            var memorias = CargarMemorias(boardId);
            var microId = CargarMicroId(bajas.NumInv);
            var microTecn = CargarTecnMicro(microId);

            var modeloBaja = baja(bajas.id, bajas.Equipo, bajas.fechaBaja, bajas.NumInv, bajas.NumSerie, bajas.Marca, discos, memorias, boardId, microTecn, marcaBoard);

            if (bajas == null)
            {
                return NotFound();
            }

            return View(modeloBaja);
        }

        // POST: Bajas/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bajas == null)
            {
                return Problem("Entity set 'ComputadoraContext.Bajas'  is null.");
            }
            var bajas = await _context.Bajas.FindAsync(id);
            if (bajas != null)
            {
                _context.Bajas.Remove(bajas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        //Controlador de impresion

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult Imprimir()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult ImprimirFilter()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        // GET: Customers/ContactPDF
        [HttpPost]
        public async Task<IActionResult> Imprimir(string Equipo)
        {

            var BuscarEquipos = from baja in _context.Bajas
                                where baja.Equipo == Equipo
                                select baja;

            var ArrBuscarEquipos = BuscarEquipos.ToArray();

            if (ArrBuscarEquipos.Length != 0)
            {
                return new ViewAsPdf("Imprimir", await BuscarEquipos.ToListAsync())
                {
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                };
            }

            return View();

        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Print(int? id)
        {
            if (id == null || _context.Bajas == null)
            {
                return NotFound();
            }

            var bajas = await _context.Bajas
                .FirstOrDefaultAsync(m => m.id == id);

            var boardId = CargarMotherboardId(bajas.NumInv);
            var marcaBoard = CargarMotherboardMarca(boardId);
            var discos = CargarDisco(boardId);
            var memorias = CargarMemorias(boardId);
            var microId = CargarMicroId(bajas.NumInv);
            var microTecn = CargarTecnMicro(microId);

            var modeloBaja = baja(bajas.id, bajas.Equipo, bajas.fechaBaja, bajas.NumInv, bajas.NumSerie, bajas.Marca, discos, memorias, boardId, microTecn, marcaBoard);

            if (bajas == null)
            {
                return NotFound();
            }


            return new ViewAsPdf("DetailsPrint", modeloBaja)
            {
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
            };
        }

        public ActionResult HeaderPdf()
        {
            return View("HeaderPDF");
        }

        public ActionResult FooterPdf()
        {
            return View("FooterPDF");
        }


        //Fin del controlador de impresion


        //metodos privados

        private bool BajasExists(int id)
        {
            return (_context.Bajas?.Any(e => e.id == id)).GetValueOrDefault();
        }

        private string CargarMotherboardId(string invPc)
        {
            //var usuariofinal = await _context.Users.FirstOrDefaultAsync(m => m.username == _user.username && m.password == _user.password);
            var Computadora = _context.Bajas.FirstOrDefault(c => c.NumInv == invPc);
            var MotherBoard = _context.MotherBoards.FirstOrDefault(b => b.NumSerieBoard == Computadora.SerieBoard);
            if (MotherBoard == null)
            {
                return "Sin Board";
            }

            return MotherBoard.NumSerieBoard.ToString();
        }

        private string CargarMotherboardMarca(string idBoard)
        {
            //var usuariofinal = await _context.Users.FirstOrDefaultAsync(m => m.username == _user.username && m.password == _user.password);
            var MotherBoard = _context.MotherBoards.FirstOrDefault(b => b.NumSerieBoard == idBoard);
            if (MotherBoard == null)
            {
                return "-";
            }

            return MotherBoard.Marca;
        }

        private string CargarMicroId(string invPc)
        {
            //var usuariofinal = await _context.Users.FirstOrDefaultAsync(m => m.username == _user.username && m.password == _user.password);
            var Computadora = _context.Bajas.FirstOrDefault(c => c.NumInv == invPc);

            var MotherBoard = _context.MotherBoards.FirstOrDefault(b => b.NumSerieBoard == Computadora.SerieBoard);
            if (MotherBoard == null)
            {
                return "-";
            }
            var micro = _context.MicroProcesadores.FirstOrDefault(m => m.NumSerieId == MotherBoard.MicroProcesadorId);


            return micro.NumSerieMicro;
        }

        private string CargarTecnMicro(string id)
        {

Views/Bajas/Delete.cshtml
@model ProyectoInventarioASP.Models.Bajas

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1 class="h1 text-danger">Eliminar</h1>

<h3 class="h3">Estas seguro que deseas eliminar esto?</h3>
<div>
    <h4 class="h4">Baja No: @Html.DisplayFor(model => model.id)</h4>
    <hr />
   <div class="container">
        <div class="row">
            @if (Model.Equipo == "computadora")
            {
                <div class="col p-2">@Html.DisplayNameFor(model => model.Equipo)</div>
                <div class="col p-2">@Html.DisplayFor(model => model.Equipo)</div>
                <div class="w-100"></div>
                <div class="col p-2">@Html.DisplayNameFor(model => model.NumInv)</div>
                <div class="col p-2">@Html.DisplayFor(model => model.NumInv)</div>
                <div class="w-100"></div>
                <div class="col p-2">@Html.DisplayNameFor(model => model.Micro.Tecnologia)
                </div>
                <div class="col p-2">@Html.DisplayFor(model => model.Micro.Tecnologia)</div>
                <div class="w-100"></div>
                <div class="col p-2">@Html.DisplayNameFor(model => model.SerieBoard)</div>
                <div class="col p-2">@Html.DisplayFor(model => model.SerieBoard)</div>
                <div class="w-100"></div>
                <div class="col p-2">@Html.DisplayNameFor(model => model.MotherBoard.Marca)</div>
                <div class="col p-2">@Html.DisplayFor(model => model.MotherBoard.Marca)</div>
                <div class="w-100"></div>
                if (Model.Memorias.Count() == 0)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 bg-danger border d-flex justify-content-between">
                        <div>Esta Pc no tiene memoria Ram</div>
                    </div>
                }
                if (Model.Discos.Count() == 0)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 bg-danger border d-flex justify-content-between">
                        <div>Esta Pc no tiene Discos duros</div>
                    </div>
                }
                foreach (var memoria in Model.Memorias)
                {

                    <div class="w-100"></div>
                    <div class="col p-2  border">No Serie De la memoria: @memoria.NumSerieMemoria</div>
                    <div class="col p-2  border">Marca de la memoria: @memoria.Marca</div>
                    <div class="col p-2  border">Capacidad de la memoria: @memoria.Capacidad</div>
                }


                foreach (var disco in Model.Discos)
                {
                    <div class="w-100"></div>
                    <div class="col p-2  border">No Serie Disco: @disco.NumSerieDisco</div>
                    <div class="col p-2  border">Marca del Disco: @disco.Marca</div>
                    <div class="col p-2  border">Capacidad del disco: @disco.Capacidad</div>

                }
            }
            else
            {
                <div class="col p-2  border">@Html.DisplayNameFor(model => model.Equipo)</div>
                <div class="col p-2  border">@Html.DisplayFor(model => model.Equipo)</div>
                <div class="w-100"></div>
                <div class="col p-2  border">@Html.DisplayNameFor(model => model.NumInv)</div>
                <div class="col p-2  border">@Html.DisplayFor(model => model.NumInv)</div>
                <div class="w-100"></div>
                <div class="col p-2  border">@Html.DisplayNameFor(model => model.Marca)</div>
                <div class="col p-2  border">@Html.DisplayFor(model => model.Marca)</div>
                <div class="w-100"></div>
                <div class="col p-2  border">@Html.DisplayNameFor(model => model.NumSerie)</div>
                <div class="col p-2  border">@Html.DisplayFor(model => model.NumSerie)</div>
                <div class="w-100"></div>

            }


        </div>
    </div>
</div>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Bajas/Details.cshtml
@model ProyectoInventarioASP.Models.Bajas

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1 class="h1">Detalles</h1>

<div>
    <h4 class="h4">Baja No: @Model.id</h4>
    <hr />
    <div class="container">
        <div class="row">
            @if (Model.Equipo == "computadora")
            {
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.Equipo)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.Equipo)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.NumInv)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.NumInv)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">Tecnologia del micro</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.Micro.Tecnologia)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.SerieBoard)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.SerieBoard)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.MotherBoard.Marca)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.MotherBoard.Marca)</div>
                <div class="w-100"></div>
                if (Model.Memorias.Count() == 0)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 bg-danger border d-flex justify-content-between">
                        <div>Esta Pc no tiene memoria Ram</div>
                    </div>
                }
                if (Model.Discos.Count() == 0)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 bg-danger border d-flex justify-content-between">
                        <div>Esta Pc no tiene Discos duros</div>
                    </div>
                }
                foreach (var memoria in Model.Memorias)
                {

                    <div class="w-100"></div>
                    <div class="col p-2 border">No Serie De la memoria: @memoria.NumSerieMemoria</div>
                    <div class="col p-2 border">Marca de la memoria: @memoria.Marca</div>
                    <div class="col p-2 border">Capacidad de la memoria: @memoria.Capacidad</div>
                }


                foreach (var disco in Model.Discos)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 border">No Serie Disco: @disco.NumSerieDisco</div>
                    <div class="col p-2 border">Marca del Disco: @disco.Marca</div>
                    <div class="col p-2 border">Capacidad del disco: @disco.Capacidad</div>

                }
            }
            else
            {
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.Equipo)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.Equipo)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.NumInv)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.NumInv)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.Marca)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.Marca)</div>
                <div class="w-100"></div>
                <div class="col p-2 border">@Html.DisplayNameFor(model => model.NumSerie)</div>
                <div class="col p-2 border">@Html.DisplayFor(model => model.NumSerie)</div>
                <div class="w-100"></div>

            }



        </div>
    </div>
</div>
<div class="container-flex p-2">
    @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.id" class="btn btn-orange btn-sm">Modificar</a>
        <a asp-action="Print" asp-route-id="@Model?.id" class="btn btn-orange btn-sm">Imprimir</a>
    }
    <a asp-action="Index" class="btn btn-orange btn-sm">Volver</a>
</div>

Views/Bajas/DetailsPrint.cshtml
@model Bajas

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactPDF</title>
    <link rel="shortcut icon" href="~/Assets/logo.png" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />

</head>

<body>
   <div>
    <h4 class="h4">Baja No: @Model.id</h4>
    <hr />
    <div class="container">
        <div class="row">
            @if (Model.Equipo == "computadora")
            {
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.Equipo) : @Html.DisplayFor(model => model.Equipo)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.NumInv) : @Html.DisplayFor(model => model.NumInv)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>Tecnologia del micro: @Html.DisplayFor(model => model.Micro.Tecnologia)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.SerieBoard) : @Html.DisplayFor(model => model.SerieBoard)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.MotherBoard.Marca) : @Html.DisplayFor(model => model.MotherBoard.Marca)</p></div>
                <div class="w-100"></div>
                foreach (var memoria in Model.Memorias)
                {

                    <div class="w-100"></div>
                    <div class="col p-2 border">No Serie De la memoria: @memoria.NumSerieMemoria</div>
                    <div class="col p-2 border">Marca de la memoria: @memoria.Marca</div>
                    <div class="col p-2 border">Capacidad de la memoria: @memoria.Capacidad</div>
                }


                foreach (var disco in Model.Discos)
                {
                    <div class="w-100"></div>
                    <div class="col p-2 border">No Serie Disco: @disco.NumSerieDisco</div>
                    <div class="col p-2 border">Marca del Disco: @disco.Marca</div>
                    <div class="col p-2 border">Capacidad del disco: @disco.Capacidad</div>

                }
            }
            else
            {
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.Equipo) : @Html.DisplayFor(model => model.Equipo)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.NumInv) : @Html.DisplayFor(model => model.NumInv)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.Marca) : @Html.DisplayFor(model => model.Marca)</p></div>
                <div class="w-100"></div>
                <div class="col p-2 border"><p>@Html.DisplayNameFor(model => model.NumSerie) : @Html.DisplayFor(model => model.NumSerie)</p></div>
                <div class="w-100"></div>

            }



        </div>
    </div>
</div>
</body>

</html>

Views/Bajas/Edit.cshtml
@model ProyectoInventarioASP.Models.Bajas

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1 class="h1">Modificar</h1>

<h4 class="h4">Bajas</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form asp-action="Edit">
            @if (Model.Equipo == "Computadora")
            {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="id" />
                <div class="form-group">
                    <label asp-for="Equipo" class="control-label"></label>
                    <input asp-for="Equipo" placeholder="Inserta el equipo" class="form-control border border-1" />
                    <span asp-validation-for="Equipo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumInv" class="control-label"></label>
                    <input asp-for="NumInv" placeholder="Inserta el inventario" class="form-control border border-1" />
                    <span asp-validation-for="NumInv" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="NumSerie" type="hidden" />
                </div>
                <div class="form-group">
                    <input asp-for="Marca" type="hidden" />
                </div>
                <div class="form-group">
                    <label asp-for="fechaBaja" class="control-label"></label>
                    <input asp-for="fechaBaja" placeholder="Inserta la fecha que se le dio baja"
                    class="form-control border border-1" />
                    <span asp-validation-for="fechaBaja" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SerieBoard" class="control-label"></label>
                    <input asp-for="SerieBoard" list="boards" class="form-control border border-1" />
                    <datalist id="boards">
                        @foreach (var board in ViewBag.Boards)
                        {
                            <option value="@board.NumSerieBoard">@board.NumSerieBoard</option>
                        }
                    </datalist>
                    <span asp-validation-for="SerieBoard" class="text-danger"></span>
                </div>
                <div class="form-group p-2">
                    <input type="submit" value="Guardar" class="btn btn-orange" />
                </div>

            }
            else
            {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="id" />
                <div class="form-group">
                    <label asp-for="Equipo" class="control-label"></label>
                    <input asp-for="Equipo" placeholder="Inserta el equipo" class="form-control border border-1" />
                    <span asp-validation-for="Equipo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumInv" class="control-label"></label>
                    <input asp-for="NumInv" placeholder="Inserta el inventario del equipo"
                    class="form-control border border-1" />
                    <span asp-validation-for="NumInv" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumSerie" class="control-label"></label>
                    <input asp-for="NumSerie" placeholder="Inserta el numero de serie"
                    class="form-control border border-1" />
                    <span asp-validation-for="NumSerie" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Marca" class="control-label"></label>
                    <input asp-for="Marca" placeholder="Inserta la marca del equipo" class="form-control border border-1" />
                    <span asp-validation-for="Marca" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="fechaBaja" class="control-label"></label>
                    <input asp-for="fechaBaja" placeholder="Inserta la fecha que se le dio baja"
                    class="form-control border border-1" />
                    <span asp-validation-for="fechaBaja" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="SerieBoard" type="hidden" class="form-control border border-1" />
                </div>
                <div class="form-group p-2">
                    <input type="submit" value="Guardar" class="btn btn-orange" />
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Bajas/FooterPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactFooterPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #ffd800; padding: 0px; margin: 0px;">
    <div class="text-center">
        <strong>
            Página <span id='page'></span> de
            <span id='topage'></span>
        </strong>        

        <script>
            var vars = {};
            var x = window.location.search.substring(1).split('&');
            for (var i in x) {
                var z = x[i].split('=', 2);
                vars[z[0]] = unescape(z[1]);
            }
            document.getElementById('page').innerHTML = vars.page;
            document.getElementById('topage').innerHTML = vars.topage;
        </script>

    </div>
</body>
</html>

Views/Bajas/HeaderPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HeaderPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #00ffff; padding: 0px; margin: 0px;">
    <div class="row">
        <div class="col-xs-4">
            <img src="~/images/generic-logo.png" />
        </div>
        <div class="col-xs-8 text-right">
            <h2>Customers Lista</h2>
        </div>
    </div>
</body>
</html>

Views/Bajas/ImprimirFilter.cshtml
@model ProyectoInventarioASP.Models.Bajas

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}
 
    <h1>Imprimir</h1>

    <h4>Ingrese un que equipo de los que se le han dado baja quieres imprimir</h4>
    <hr />

    <form method="post" asp-controller="Bajas", asp-action="Imprimir">
           <div class="form-row col-md-5 border border-1">
            <div class="form-group">
                <label asp-for="Equipo" class="control-label"></label>
                <input asp-for="Equipo" class="form-control border border-5" required />
            </div>

            <div class="form-group col-md-6">
                <input type="submit" value="Buscar" class="btn btn-orange" />
            </div>
        </div>
    </form>

    <div>
        <a asp-action="Index">Volver</a>
    </div>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }