Models/Scanner.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
namespace ProyectoInventarioASP.Models
{
    public class Scanner
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        [Display(Name = "Serial")]
        public string NumSerie { get; set; }

        [Required(ErrorMessage ="Este Campo es requerido")]
        [Display(Name = "Inventario")]
        public string NumInv { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        public string Marca { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        public Estado estado { get; set; }

        [Display(Name = "Usuario No")]
        [ForeignKey("UsuarioId")]
        public int UsuarioId { get; set; }
        [Display(Name = "Nombre del Usuario")]
        [Required(ErrorMessage ="Este Campo es requerido")]
        public string UserName { get; set; }

        [JsonIgnore]
        [NotMapped]
        public virtual ICollection<Computadora> Computadora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}

Controllers/ScannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoInventarioASP;
using ProyectoInventarioASP.Models;
using Rotativa.AspNetCore;

namespace ProyectoInventarioASP.Controllers
{
    [Authorize]
    public class ScannerController : Controller
    {
        private readonly ComputadoraContext _context;

        public ScannerController(ComputadoraContext context)
        {
            _context = context;
        }

        // GET: Scanner
        public async Task<IActionResult> Index()
        {
            var computadoraContext = _context.Scanners.Include(s => s.Usuario);
            return View(await computadoraContext.ToListAsync());
        }

        // GET: Scanner/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Scanners == null)
            {
                return NotFound();
            }

            var scanner = await _context.Scanners
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scanner == null)
            {
                return NotFound();
            }

            return View(scanner);
        }

        // GET: Scanner/Create
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Create(string NombreUsuario = null, int? UsuarioId = null)
        {
            var scanner = new Scanner();
            ViewBag.Trabajadores = await _context.Usuarios.ToListAsync();
            if (NombreUsuario == null && UsuarioId == null)
            {
                ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario");
                return View();
            }

            if (NombreUsuario != null)
            {
                var esUsuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.NombreUsuario == NombreUsuario);
                //List<Usuario> ListUsuario = new List<Usuario>();
                //ListUsuario.Add(esUsuario);
                // ViewData["EntradaId"] = new SelectList(entrada.ToList(), "Id", "Id");
                //ViewData["NombreUser"] = new SelectList(ListUsuario, "NombreUsuario", "NombreUsuario");
                scanner.UserName = esUsuario.NombreUsuario;
                return View(scanner);
            }

            var esUsuarioId = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == UsuarioId);
            //List<Usuario> ListUsuarioPorId = new List<Usuario>();
            //ListUsuarioPorId.Add(esUsuarioId);
            // ViewData["EntradaId"] = new SelectList(entrada.ToList(), "Id", "Id");
            //ViewData["NombreUser"] = new SelectList(ListUsuarioPorId, "NombreUsuario", "NombreUsuario");
            scanner.UserName = esUsuarioId.NombreUsuario;
            return View(scanner);

        }

        // POST: Scanner/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Scanner scanner)
        {
            if (scanner != null)
            {
                try
                {
                    if (scanner.Marca == null || scanner.NumInv == null || scanner.NumInv == null || scanner.NumSerie == null || scanner.UserName == null)
                    {
                        ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", scanner.UserName);
                        return View(scanner);
                    }
                    //Cargar los Id de los usuarios
                    var BuscarIdUser = from user in _context.Usuarios
                                       where user.NombreUsuario == scanner.UserName
                                       select user.Id;

                    var idUser = BuscarIdUser.ToArray();
                    scanner.UsuarioId = idUser[0];
                    _context.Add(scanner);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                catch (SystemException)
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", scanner.UserName);
            return View(scanner);
        }

        // GET: Scanner/Edit/5
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Scanners == null)
            {
                return NotFound();
            }

            var scanner = await _context.Scanners.FindAsync(id);
            if (scanner == null)
            {
                return NotFound();
            }
            //ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario");
            ViewBag.Trabajadores = await _context.Usuarios.ToListAsync();
            return View(scanner);
        }

        // POST: Scanner/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NumSerie,NumInv,Marca,estado,UsuarioId,UserName")] Scanner scanner)
        {
            if (id != scanner.Id)
            {
                return NotFound();
            }

            if (scanner != null)
            {
                try
                {
                    if (scanner.Marca == null || scanner.NumInv == null || scanner.NumInv == null || scanner.NumSerie == null || scanner.UserName == null)
                    {
                        ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", scanner.UserName);
                        return View(scanner);
                    }
                    //Cargar los Id de los usuarios
                    var BuscarIdUser = from user in _context.Usuarios
                                       where user.NombreUsuario == scanner.UserName
                                       select user.Id;

                    var idUser = BuscarIdUser.ToArray();
                    scanner.UsuarioId = idUser[0];
                    _context.Update(scanner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScannerExists(scanner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", scanner.UserName);
            return View(scanner);
        }

        // GET: Scanner/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Scanners == null)
            {
                return NotFound();
            }

            var scanner = await _context.Scanners
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (scanner == null)
            {
                return NotFound();
            }

            return View(scanner);
        }

        // POST: Scanner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
         [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Scanners == null)
            {
                return Problem("Entity set 'ComputadoraContext.Scanners'  is null.");
            }
            var scanner = await _context.Scanners.FindAsync(id);
            if (scanner != null)
            {
                _context.Scanners.Remove(scanner);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Controlador de impresion

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult Imprimir()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult ImprimirFilter()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        // GET: Customers/ContactPDF
        [HttpPost]
        public async Task<IActionResult> Imprimir(string NumInv)
        {

            var BuscarMarc = from scan in _context.Scanners
                             where scan.Marca == NumInv
                             select scan;

            var ArrBuscarMarc = BuscarMarc.ToArray();

            if (ArrBuscarMarc.Length != 0)
            {
                return new ViewAsPdf("Imprimir", await BuscarMarc.ToListAsync())
                {
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                };
            }
            else
            {
                if (NumInv == "activo" || NumInv == "inactivo")
                {
                    if (NumInv == "activo")
                    {

Views/Scanner/Create.cshtml
@model ProyectoInventarioASP.Models.Scanner

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1 class="h1">Crear</h1>

<h4 class="h4">Scanner</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumSerie" class="control-label"></label>
                <input asp-for="NumSerie" placeholder="Introduzca el numero de serie del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="NumSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" placeholder="Introduzca el inventario del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="NumInv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" placeholder="Introduzca la marca del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" placeholder="Introduzca un usuario responsable del scanner"
                    class="form-control border border-5" list="usuarios" />
                <datalist id="usuarios">
                    @foreach (var item in ViewBag.Trabajadores)
                    {
                        <option value="@item.NombreUsuario">@item.NombreUsuario</option>
                    }
                </datalist>
            </div>
            <div class="form-group">
                <label asp-for="estado"></label>
                @Html.DropDownList(
                "estado", Html.GetEnumSelectList<Estado>(),
                "Seleccione un estado",
                new{@class = "form-control"}
                )
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Crear" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Scanner/Delete.cshtml
@model ProyectoInventarioASP.Models.Scanner

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1 class="h1 text-danger">Dar Baja</h1>

<h3 class="h3">Estas a punto de darle baja este scanner, estas seguro?</h3>
<div>
    <h4>Scanner No: @Html.DisplayFor(model => model.Id)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumInv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumInv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Cargo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Dar Baja" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Scanner/Details.cshtml
@model ProyectoInventarioASP.Models.Scanner

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<   /h1>

<div>
    <h4>Scanner No: @Html.DisplayFor(model => model.Id)</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.NumInv)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.NumInv)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.Marca)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.Marca)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.NumSerie)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.NumSerie)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.estado)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.estado)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.UserName)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.UserName)</div>
        </div>
    </div>
    <div class="container-flex">
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Modificar</a>
        <td><a asp-action="Print" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Imprimir</a></td>
        <a asp-action="Index">Volver</a>
    </div>

Views/Scanner/DetailsPrint.cshtml
@model Scanner

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactPDF</title>
    <link rel="shortcut icon" href="~/Assets/logo.png" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>

<body>

    <div>
        <h4>Scanner No: @Html.DisplayFor(model => model.Id)</h4>
        <hr />
         <div class="container">
            <div class="row">
                <div class="col p-2 border">
                    <p>@Html.DisplayNameFor(model => model.NumInv) : @Html.DisplayFor(model => model.NumInv)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.Marca) : @Html.DisplayFor(model => model.Marca)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.NumSerie) : @Html.DisplayFor(model => model.NumSerie)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.estado) : @Html.DisplayFor(model => model.estado)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.UserName) : @Html.DisplayFor(model => model.UserName)</p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Views/Scanner/Edit.cshtml
@model ProyectoInventarioASP.Models.Scanner

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>

<h4>Scanner</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumSerie" class="control-label"></label>
                <input asp-for="NumSerie" placeholder="Introduzca el numero de serie del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="NumSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" placeholder="Introduzca el inventario del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="NumInv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" placeholder="Introduzca la marca del scanner"
                    class="form-control border border-5" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" placeholder="Introduzca un usuario responsable del scanner"
                    class="form-control border border-5" list="usuarios" />
                <datalist id="usuarios">
                    @foreach (var item in ViewBag.Trabajadores)
                    {
                        <option value="@item.NombreUsuario">@item.NombreUsuario</option>
                    }
                </datalist>
            </div>
            <div class="form-group">
                <label asp-for="estado"></label>
                @Html.DropDownList(
                "estado", Html.GetEnumSelectList<Estado>(),
                "Seleccione un estado",
                new{@class = "form-control"}
                )
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Guardar" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Scanner/FooterPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactFooterPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #ffd800; padding: 0px; margin: 0px;">
    <div class="text-center">
        <strong>
            Página <span id='page'></span> de
            <span id='topage'></span>
        </strong>        

        <script>
            var vars = {};
            var x = window.location.search.substring(1).split('&');
            for (var i in x) {
                var z = x[i].split('=', 2);
                vars[z[0]] = unescape(z[1]);
            }
            document.getElementById('page').innerHTML = vars.page;
            document.getElementById('topage').innerHTML = vars.topage;
        </script>

    </div>
</body>
</html>

Views/Scanner/HeaderPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HeaderPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #00ffff; padding: 0px; margin: 0px;">
    <div class="row">
        <div class="col-xs-4">
            <img src="~/images/generic-logo.png" />
        </div>
        <div class="col-xs-8 text-right">
            <h2>Customers Lista</h2>
        </div>
    </div>
</body>
</html>

Views/Scanner/Imprimir.cshtml
@model IEnumerable<Scanner>

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactPDF</title>
    <link rel="shortcut icon" href="~/Assets/logo.png" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <style>
        /* SOLUCIONA PROBLEMA DE SOLAPAMIENTO EN TABLAS <table /> */
        thead {
            display: table-header-group
        }

        tfoot {
            display: table-row-group
        }

        tr {
            page-break-inside: avoid
        }
    </style>

</head>

<body>
      <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumInv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estado)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumSerie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumInv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                 <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
            </tr>
        }
    </tbody>
</table>

</body>

</html>

Views/Scanner/ImprimirFilter.cshtml
@model ProyectoInventarioASP.Models.Scanner

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}
 
    <h1>Imprimir</h1>

    <h4>Ingrese un dato de los scanner que quieres imprimir</h4>
    <hr />

    <form method="post" asp-controller="Scanner", asp-action="Imprimir">
           <div class="form-row border border-1">
            <div class="form-group col-md-6">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" class="form-control border border-5" required />
            </div>

            <div class="form-group col-md-6">
                <input type="submit" value="Buscar" class="btn btn-orange" />
            </div>
        </div>
    </form>

    <div>
        <a asp-action="Index">Volver</a>
    </div>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/Scanner/Index.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Scanner>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>Scaners</h1>

<p>
    @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
    {
    <div class="container-flex">
        <p>
            <a asp-action="Create" class="btn btn-orange btn-sm">Insertar</a>
        </p>
        <p>
            <a asp-action="ImprimirFilter" class="btn btn-orange btn-sm" id="guardar">Imprimir Todos</a>
        </p>
    </div>
    }
</p>
<div class="table-responsive">
<table class="table table-hover table-border" id="tabla">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumInv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estado)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="CuerpoTablaPc">
        @foreach (var item in Model)
        {
            <tr class="filapc">
                <td>
                    @Html.DisplayFor(modelItem => item.NumSerie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumInv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
                {
                    <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                    <td><a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm"> baja</a></td>
                }
                @if (User.IsInRole("lectura"))
                {
                    <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                }
            </tr>
        }
    </tbody>
</table>
</div>