Models/Salida.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ProyectoInventarioASP.Models
{
    public class Salida
    {
        [Key]
        public string Id { get; set; }


        [Display(Name = "Quien Se lo lleva")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        public string salida { get; set; }

        [Display(Name = "Fecha Entrega")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        public DateTime FechaSalida { get; set; }
        public int EntradaId { get; set; }

        [MaxLength(150, ErrorMessage = "Las observaciones deben tener como maximo 150caracteres")]
        [Required(ErrorMessage = "Este Campo es requerido")]
        public string observaciones { get; set; }

        public Entrada entradas { get; set; }




    }
}

Controllers/SalidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoInventarioASP;
using ProyectoInventarioASP.Models;

namespace ProyectoInventarioASP.Controllers
{
    [Authorize]
    public class SalidaController : Controller
    {
        private readonly ComputadoraContext _context;

        public SalidaController(ComputadoraContext context)
        {
            _context = context;
        }

        // GET: Salida
        public async Task<IActionResult> Index()
        {
            var computadoraContext = _context.Salidas.Include(s => s.entradas);
            return View(await computadoraContext.ToListAsync());
        }

        // GET: Salida/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Salidas == null)
            {
                return NotFound();
            }

            var salida = await _context.Salidas
                .Include(s => s.entradas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salida == null)
            {
                return NotFound();
            }

            return View(salida);
        }

        // GET: Salida/Create
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Create(int? id)
        {
            var salida = from sali in _context.Salidas
                         where sali.EntradaId == id
                         select sali;

            if (salida.ToList().Count() != 0)
            {
                return RedirectToAction("RegistroError", "Home");
            }

            var Entrada = await _context.Entradas.Where(e => e.Id == id).FirstOrDefaultAsync();
            if (Entrada == null)
            {
                return View();
            }
            var FechaSalida = new Salida();
            FechaSalida.FechaSalida = DateTime.Now;
            FechaSalida.EntradaId = Entrada.Id;
            FechaSalida.Id = Entrada.Id.ToString();
            return View(FechaSalida);
        }

        // POST: Salida/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(string Id, string salida, DateTime FechaSalida, int EntradaId, string observaciones)
        {
            var Salida = new Salida();
            Salida.Id = Id;
            Salida.salida = salida;
            Salida.FechaSalida = FechaSalida;
            Salida.EntradaId = EntradaId;
            Salida.observaciones = observaciones;

            if (Salida != null)
            {
                try
                {
                    if (Salida.EntradaId == null || Salida.FechaSalida == null || Salida.Id == null || Salida.observaciones == null || Salida.salida == null)
                    {
                        ViewData["EntradaId"] = new SelectList(_context.Entradas, "Id", "Id", Salida.EntradaId);
                        return View();
                    }
                    _context.Add(Salida);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Entrada", Salida);
                }
                catch (System.Exception)
                {

                    return RedirectToAction("Index", "Home");
                }

            }
            return View();
        }

        // GET: Salida/Edit/5
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Salidas == null)
            {
                return NotFound();
            }

            var salida = await _context.Salidas.FindAsync(id);
            if (salida == null)
            {
                return NotFound();
            }
            return View(salida);
        }

        // POST: Salida/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string salida, DateTime FechaSalida, int EntradaId, string observaciones)
        {
            var Salida = new Salida();
            Salida.Id = id;
            Salida.salida = salida;
            Salida.FechaSalida = FechaSalida;
            Salida.EntradaId = EntradaId;
            Salida.observaciones = observaciones;
            if (id != Salida.Id)
            {
                return NotFound();
            }

            if (Salida != null)
            {
                try
                {
                    if (Salida.salida == null || Salida.FechaSalida == null || Salida.Id == null || Salida.observaciones == null || Salida.EntradaId == null)
                    {
                        return View(Salida);
                    }
                    _context.Update(Salida);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalidaExists(Salida.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Salida);
        }

        // GET: Salida/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Salidas == null)
            {
                return NotFound();
            }

            var salida = await _context.Salidas
                .Include(s => s.entradas)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (salida == null)
            {
                return NotFound();
            }

            return View(salida);
        }

        // POST: Salida/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Salidas == null)
            {
                return Problem("Entity set 'ComputadoraContext.Salidas'  is null.");
            }
            var salida = await _context.Salidas.FindAsync(id);
            if (salida != null)
            {
                _context.Salidas.Remove(salida);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalidaExists(string id)
        {
            return (_context.Salidas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Salida/Create.cshtml
@model Salida

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Insertar</h1>

<h4>Salida</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form method="post" asp-controller="Salida" asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salida" class="control-label"></label>
                <input asp-for="salida" class="form-control border border-5" />
                <span asp-validation-for="salida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label"></label>
                <input asp-for="FechaSalida" class="form-control border border-2" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="EntradaId" class="form-control" type="hidden">
            </div>
            <div class="mb-3">
                <label asp-for="observaciones" class="form-label">Observaciones: </label>
                <textarea class="form-control border border-2" asp-for="observaciones" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Dar Salida" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Salida/Delete.cshtml
@model ProyectoInventarioASP.Models.Salida

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1 class="h1 text danger">Eliminar</h1>

<h3>Estas seguro que deseas eliminar esto?</h3>
<div>
    <h4>Salida</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.salida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.observaciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.observaciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.entradas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.entradas.Entrega)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Salida/Details.cshtml
@model ProyectoInventarioASP.Models.Salida

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Detalles de la salida</h1>

<div>
    <h4>Salida No: @Html.DisplayFor(model => model.Id)</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.salida)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.salida)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.FechaSalida)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.FechaSalida)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.observaciones)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.observaciones)</div>
        </div>
    </div>
    <div class="container-flex p-2">
        @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
        {
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Modificar</a>
            <a asp-action="Print" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Imprimir</a>
        }
        <a asp-action="Index" class="btn btn-orange btn-sm">Volver</a>
    </div>

Views/Salida/Edit.cshtml
@model ProyectoInventarioASP.Models.Salida

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1 class="h1">Modificar</h1>

<h4 class="h4">Salida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="salida" class="control-label"></label>
                <input asp-for="salida" class="form-control border border-5" />
                <span asp-validation-for="salida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label"></label>
                <input asp-for="FechaSalida" class="form-control border border-2" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="EntradaId" class="form-control" type="hidden">
            </div>
            <div class="mb-3">
                <label asp-for="observaciones" class="form-label">Observaciones: </label>
                <textarea class="form-control border border-2" asp-for="observaciones" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Dar Salida" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Salida/Index.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Salida>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1 class="h1">Salidas</h1>

<div class="table-responsive">
    <table class="table table-hover" id="tabla">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.salida)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaSalida)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.observaciones)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.entradas)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="CuerpoTablaPc">
            @foreach (var item in Model)
            {
                <tr class="filapc">
                    <td>
                        @Html.DisplayFor(modelItem => item.salida)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaSalida)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.observaciones)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.entradas.Entrega)
                    </td>
                    @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
                    {
                        <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                        <td><a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a></td>
                    }

                    @if (User.IsInRole("lectura"))
                    {
                        <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>