Models/Ups.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ProyectoInventarioASP.Models
{
    public class Ups
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        public String NumSerie { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        public String NumInv { get; set; }
        [Required(ErrorMessage ="Este Campo es requerido")]
        public String Marca { get; set; }

        [Required(ErrorMessage ="Este Campo es requerido")]
        public Estado estado { get; set; }
        [Display(Name = "Usuario No")]
        [ForeignKey("UsuarioId")]
        public int UsuarioId { get; set; }
        [Display(Name = "Nombre del Usuario")]
        [Required(ErrorMessage ="Este Campo es requerido")]
        public string UserName { get; set; }

        [JsonIgnore]
        public virtual ICollection<Computadora> Computadora { get; set; }
        
    
        public virtual Usuario Usuario { get; set; }
    }
}

Controllers/UpsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoInventarioASP;
using ProyectoInventarioASP.Models;
using Rotativa.AspNetCore;

namespace ProyectoInventarioASP.Controllers
{
    [Authorize]
    public class UpsController : Controller
    {
        private readonly ComputadoraContext _context;

        public UpsController(ComputadoraContext context)
        {
            _context = context;
        }

        // GET: Ups
        public async Task<IActionResult> Index()
        {
            return _context.Upss != null ?
                        View(await _context.Upss.ToListAsync()) :
                        Problem("Entity set 'ComputadoraContext.Upss'  is null.");
        }

        // GET: Ups/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0 || _context.Upss == null)
            {
                return NotFound();
            }

            var ups = await _context.Upss
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ups == null)
            {
                return NotFound();
            }

            return View(ups);
        }

        // GET: Ups/Create
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Create(string NombreUsuario)
        {
            if (NombreUsuario == null)
            {
                var Trabajadores = await _context.Usuarios.ToListAsync();
                ViewBag.Trabajadores = Trabajadores;

                return View();
            }
            var esUsuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.NombreUsuario == NombreUsuario);
            List<Usuario> ListUsuario = new List<Usuario>();
            ListUsuario.Add(esUsuario);
            // ViewData["EntradaId"] = new SelectList(entrada.ToList(), "Id", "Id");
            ViewData["NombreUser"] = new SelectList(ListUsuario, "NombreUsuario", "NombreUsuario");
            return View();
        }

        // POST: Ups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Ups ups)
        {
            if (ups != null)
            {
                try
                {
                    if (ups.Marca == null || ups.NumInv == null || ups.NumSerie == null || ups.UserName == null)
                    {
                        ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", ups.UserName);
                        return View(ups);
                    }
                    //Cargar los Id de los usuarios
                    var BuscarIdUser = from user in _context.Usuarios
                                       where user.NombreUsuario == ups.UserName
                                       select user.Id;

                    var idUser = BuscarIdUser.ToArray();
                    ups.UsuarioId = idUser[0];
                    _context.Add(ups);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                catch (SystemException)
                {
                    return RedirectToAction("Index", "Home");
                }



            }
            ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", ups.UserName);
            return View(ups);
        }

        // GET: Ups/Edit/5
        [Authorize(Roles = "admin , lecturaYEscritura")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0 || _context.Upss == null)
            {
                return NotFound();
            }

            var ups = await _context.Upss.FindAsync(id);
            if (ups == null)
            {
                return NotFound();
            }
            var Trabajadores = await _context.Usuarios.ToListAsync();
            ViewBag.Trabajadores = Trabajadores;
            return View(ups);
        }

        // POST: Ups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin , lecturaYEscritura")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ups ups)
        {
            if (id != ups.Id)
            {
                return NotFound();
            }

            if (ups != null)
            {
                try
                {
                    if (ups.Marca == null || ups.NumInv == null || ups.NumSerie == null || ups.UserName == null)
                    {
                        ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", ups.UserName);
                        return View(ups);
                    }
                    //Cargar los Id de los usuarios
                    var BuscarIdUser = from user in _context.Usuarios
                                       where user.NombreUsuario == ups.UserName
                                       select user.Id;

                    var idUser = BuscarIdUser.ToArray();
                    ups.UsuarioId = idUser[0];
                    _context.Update(ups);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UpsExists(ups.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NombreUser"] = new SelectList(_context.Usuarios, "NombreUsuario", "NombreUsuario", ups.UserName);
            return View(ups);
        }

        // GET: Ups/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Upss == null)
            {
                return NotFound();
            }

            var ups = await _context.Upss
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ups == null)
            {
                return NotFound();
            }

            return View(ups);
        }

        // POST: Ups/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Upss == null)
            {
                return Problem("Entity set 'ComputadoraContext.Upss'  is null.");
            }
            var ups = await _context.Upss.FindAsync(id);
            if (ups != null)
            {
                var nuevaBaja = new Bajas();
                nuevaBaja.NumInv = ups.NumInv;
                nuevaBaja.NumSerie = ups.NumSerie;
                nuevaBaja.Marca = ups.Marca;
                nuevaBaja.Equipo = "UPS";
                nuevaBaja.fechaBaja = DateTime.Now;
                nuevaBaja.SerieBoard = "-";
                _context.Bajas.Add(nuevaBaja);
                _context.Upss.Remove(ups);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        //Controlador de impresion

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult Imprimir()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        public IActionResult ImprimirFilter()
        {
            return View();
        }

        [Authorize(Roles = "admin , lecturaYEscritura")]
        // GET: Customers/ContactPDF
        [HttpPost]
        public async Task<IActionResult> Imprimir(string NumInv)
        {

            var BuscarMarc = from ups in _context.Upss
                             where ups.Marca == NumInv
                             select ups;

            var ArrBuscarMarc = BuscarMarc.ToArray();

            if (ArrBuscarMarc.Length != 0)
            {
                return new ViewAsPdf("Imprimir", await BuscarMarc.ToListAsync())
                {
                    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                };
            }
            else
            {
                if (NumInv == "activo" || NumInv == "inactivo")
                {
                    if (NumInv == "activo")
                    {
                        var BuscarAct = from ups in _context.Upss
                                        where ups.estado == Estado.activo
                                        select ups;


                        var ArrBuscarAct = BuscarAct.ToArray();

                        if (ArrBuscarAct.Length != 0)
                        {
                            return new ViewAsPdf("Imprimir", await BuscarAct.ToListAsync())
                            {
                                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                            };
                        }
                    }
                    else if (NumInv == "inactivo")
                    {
                        var BuscarInac = from ups in _context.Upss
                                         where ups.estado == Estado.inactivo
                                         select ups;

Views/Ups/Create.cshtml
@model ProyectoInventarioASP.Models.Ups

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}

<h1>Insertar</h1>

<h4>Ups</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumSerie" class="control-label"></label>
                <input asp-for="NumSerie" placeholder="Inserte el numero de serie" class="form-control border border-5" />
                <span asp-validation-for="NumSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" placeholder="Inserte el numero de inventario" class="form-control border border-5" />
                <span asp-validation-for="NumInv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" placeholder="Inserte la marca" class="form-control border border-5" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            @if (ViewBag.Trabajadores == null)
            {
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <select asp-for="UserName" class="form-control" asp-items="ViewBag.NombreUser"></select>
                </div>
            }
            @if (ViewBag.Trabajadores != null)
            {
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" placeholder="Introduzca un usuario" class="form-control border border-5"
                    list="usuarios" />
                    <datalist id="usuarios">
                        @foreach (var item in ViewBag.Trabajadores)
                        {
                            <option value="@item.NombreUsuario">@item.NombreUsuario</option>
                        }
                    </datalist>
                </div>
            }
            <div class="form-group">
                <label asp-for="estado"></label>
                @Html.DropDownList(
                "estado", Html.GetEnumSelectList<Estado>(),
                "Seleccione un estado",
                new{@class = "form-control"}
                )
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Crear" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ups/Delete.cshtml
@model ProyectoInventarioASP.Models.Ups

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1 class="h1 text-danger">Dar Baja</h1>

<h3>Estas a punto de darle baja esta Ups, estas seguro?</h3>
<div>
    <h4>Ups</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumInv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumInv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Dar Baja" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Ups/Details.cshtml
@model ProyectoInventarioASP.Models.Ups

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Detalles</h1>

<div>
     <h3 class="h3">Ups No: @Html.DisplayFor(model => model.Id)</h3>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.NumInv)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.NumInv)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.Marca)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.Marca)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.NumSerie)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.NumSerie)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.estado)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.estado)</div>
            <div class="w-100"></div>
            <div class="col p-2     border">@Html.DisplayNameFor(model => model.UserName)</div>
            <div class="col p-2     border">@Html.DisplayFor(model => model.UserName)</div>
        </div>
    </div>
</div>
<div class="container-flex p-2">
        @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
        {
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Modificar</a>
            <a asp-action="Print" asp-route-id="@Model?.Id" class="btn btn-orange btn-sm">Imprimir</a>
        }
        <a asp-action="Index" class="btn btn-orange btn-sm">Volver</a>
    </div>

Views/Ups/DetailsPrint.cshtml
@model Ups

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactPDF</title>
    <link rel="shortcut icon" href="~/Assets/logo.png" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />

</head>

<body>
   <div>
    <h4>Ups No: @Html.DisplayFor(model => model.Id)</h4>
    <hr />
      <div class="container">
            <div class="row">
                <div class="col p-2 border">
                    <p>@Html.DisplayNameFor(model => model.NumInv) : @Html.DisplayFor(model => model.NumInv)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.Marca) : @Html.DisplayFor(model => model.Marca)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.NumSerie) : @Html.DisplayFor(model => model.NumSerie)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.estado) : @Html.DisplayFor(model => model.estado)</p>
                </div>
                <div class="w-100"></div>
                <div class="col p-2   border">
                    <p>@Html.DisplayNameFor(model => model.UserName) : @Html.DisplayFor(model => model.UserName)</p>
                </div>
            </div>
        </div>
</div>
</body>

</html>

Views/Ups/Edit.cshtml
@model ProyectoInventarioASP.Models.Ups

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Modificar</h1>

<h4>Ups</h4>
<hr />
<div class="row">
    <div class="col-md-5 border border-1">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumSerie" class="control-label"></label>
                <input asp-for="NumSerie" placeholder="Inserte un numero de serie" class="form-control border border-5" />
                <span asp-validation-for="NumSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" placeholder="Inserte un numero de inventario" class="form-control border border-5" />
                <span asp-validation-for="NumInv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" placeholder="Inserte la marca" class="form-control border border-5" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" placeholder="Introduzca un usuario" class="form-control border border-5"
                    list="usuarios" />
                <datalist id="usuarios">
                    @foreach (var item in ViewBag.Trabajadores)
                    {
                        <option value="@item.NombreUsuario">@item.NombreUsuario</option>
                    }
                </datalist>
            </div>
            <div class="form-group">
                <label asp-for="estado"></label>
                @Html.DropDownList(
                "estado", Html.GetEnumSelectList<Estado>(),
                "Seleccione un estado",
                new{@class = "form-control"}
                )
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Guardar" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Ups/FooterPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactFooterPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #ffd800; padding: 0px; margin: 0px;">
    <div class="text-center">
        <strong>
            Página <span id='page'></span> de
            <span id='topage'></span>
        </strong>        

        <script>
            var vars = {};
            var x = window.location.search.substring(1).split('&');
            for (var i in x) {
                var z = x[i].split('=', 2);
                vars[z[0]] = unescape(z[1]);
            }
            document.getElementById('page').innerHTML = vars.page;
            document.getElementById('topage').innerHTML = vars.topage;
        </script>

    </div>
</body>
</html>

Views/Ups/HeaderPdf.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Computadora>
@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HeaderPDF</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body style="background: #00ffff; padding: 0px; margin: 0px;">
    <div class="row">
        <div class="col-xs-4">
            <img src="~/images/generic-logo.png" />
        </div>
        <div class="col-xs-8 text-right">
            <h2>Customers Lista</h2>
        </div>
    </div>
</body>
</html>

Views/Ups/Imprimir.cshtml
@model IEnumerable<Ups>

@{
    ViewData["Title"] = "Index";
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>ContactPDF</title>
    <link rel="shortcut icon" href="~/Assets/logo.png" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <style>
        /* SOLUCIONA PROBLEMA DE SOLAPAMIENTO EN TABLAS <table /> */
        thead {
            display: table-header-group
        }

        tfoot {
            display: table-row-group
        }

        tr {
            page-break-inside: avoid
        }
    </style>

</head>

<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NumSerie)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumInv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Marca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.estado)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumSerie)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumInv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.estado)
                    </td>
                </tr>
            }
        </tbody>
    </table>


</body>

</html>

Views/Ups/ImprimirFilter.cshtml
@model ProyectoInventarioASP.Models.Ups

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
}
 
    <h1>Imprimir</h1>

    <h4>Ingrese un dato de las ups que quieres imprimir</h4>
    <hr />

    <form method="post" asp-controller="Ups", asp-action="Imprimir">
           <div class="form-row border border-1">
            <div class="form-group col-md-6">
                <label asp-for="NumInv" class="control-label"></label>
                <input asp-for="NumInv" class="form-control border border-5" required />
            </div>

            <div class="form-group col-md-6">
                <input type="submit" value="Buscar" class="btn btn-orange" />
            </div>
        </div>
    </form>

    <div>
        <a asp-action="Index">Volver</a>
    </div>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/Ups/Index.cshtml
@model IEnumerable<ProyectoInventarioASP.Models.Ups>

@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}

<h1>UPS</h1>

@if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
{
    <div class="container-flex">
        <p>
            <a asp-action="Create" class="btn btn-orange btn-sm">Insertar</a>
        </p>
        <p>
            <a asp-action="ImprimirFilter" class="btn btn-orange btn-sm" id="guardar">Imprimir Todos</a>
        </p>
    </div>
}
<div class="table-responsive">
    <table class="table table-hover table-border" id="tabla">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NumSerie)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumInv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Marca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.estado)
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody id="CuerpoTablaPc">
            @foreach (var item in Model)
            {
                <tr class="filapc">
                    <td>
                        @Html.DisplayFor(modelItem => item.NumSerie)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumInv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.estado)
                    </td>
                    @if (User.IsInRole("admin") || User.IsInRole("lecturaYEscritura"))
                    {
                        <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                        <td><a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm"> baja</a></td>
                    }

                    @if (User.IsInRole("lectura"))
                    {
                        <td><a asp-action="Details" asp-route-id="@item.Id" class="btn btn-orange btn-sm">Detalles</a></td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>